/* eslint-disable */
// Custom view imports — NOT generated by elegant-router
// These views are for dynamic routes where the backend provides route names
// that use a parent_child naming pattern (e.g. subjects_list, exams_sessions).

import type { RouteComponent } from 'vue-router';

export const customViews: Record<string, RouteComponent | (() => Promise<RouteComponent>)> = {
  subjects_list: () => import('@/views/subjects/list.vue'),
  'question-types_list': () => import('@/views/question-types/list.vue'),
  questions_list: () => import('@/views/questions/list.vue'),
  'knowledge-points_list': () => import('@/views/knowledge-points/list.vue'),
  materials_list: () => import('@/views/materials/list.vue'),
  exams_list: () => import('@/views/exams/list.vue'),
  exams_sessions: () => import('@/views/exams/sessions.vue'),
  scores_list: () => import('@/views/scores/list.vue'),
  users_list: () => import('@/views/users/list.vue'),
  rbac_permissions: () => import('@/views/rbac/permissions.vue'),
  rbac_roles: () => import('@/views/rbac/roles.vue'),
  rbac_admins: () => import('@/views/rbac/admins.vue'),
  rbac_menus: () => import('@/views/rbac/menus.vue'),
};
