/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
  subjects_list: () => import("@/views/subjects/list.vue"),
  "question-types_list": () => import("@/views/question-types/list.vue"),
  questions_list: () => import("@/views/questions/list.vue"),
  "knowledge-points_list": () => import("@/views/knowledge-points/list.vue"),
  materials_list: () => import("@/views/materials/list.vue"),
  exams_list: () => import("@/views/exams/list.vue"),
  exams_sessions: () => import("@/views/exams/sessions.vue"),
  scores_list: () => import("@/views/scores/list.vue"),
  users_list: () => import("@/views/users/list.vue"),
  rbac_permissions: () => import("@/views/rbac/permissions.vue"),
  rbac_roles: () => import("@/views/rbac/roles.vue"),
  rbac_menus: () => import("@/views/rbac/menus.vue"),
  rbac_admins: () => import("@/views/rbac/admins.vue")
};
