/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteRecordRaw, RouteComponent } from 'vue-router';
import type { ElegantConstRoute } from '@elegant-router/vue';
import type { RouteMap, RouteKey, RoutePath } from '@elegant-router/types';

export function transformElegantRoutesToVueRoutes(
  routes: ElegantConstRoute[],
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  return routes.flatMap(route => transformElegantRouteToVueRoute(route, layouts, views));
}

function transformElegantRouteToVueRoute(
  route: ElegantConstRoute,
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  const LAYOUT_PREFIX = 'layout.';
  const VIEW_PREFIX = 'view.';
  const ROUTE_DEGREE_SPLITTER = '_';
  const FIRST_LEVEL_ROUTE_COMPONENT_SPLIT = '$';

  function isLayout(component: string) {
    return component.startsWith(LAYOUT_PREFIX);
  }

  function getLayoutName(component: string) {
    const layout = component.replace(LAYOUT_PREFIX, '');
    if (!layouts[layout]) throw new Error(`Layout component "${layout}" not found`);
    return layout;
  }

  function isView(component: string) {
    return component.startsWith(VIEW_PREFIX);
  }

  function getViewName(component: string) {
    const view = component.replace(VIEW_PREFIX, '');
    if (!views[view]) throw new Error(`View component "${view}" not found`);
    return view;
  }

  function isFirstLevelRoute(item: ElegantConstRoute) {
    return !item.name.includes(ROUTE_DEGREE_SPLITTER);
  }

  function isSingleLevelRoute(item: ElegantConstRoute) {
    return isFirstLevelRoute(item) && !item.children?.length;
  }

  function getSingleLevelRouteComponent(component: string) {
    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);
    return { layout: getLayoutName(layout), view: getViewName(view) };
  }

  const vueRoutes: RouteRecordRaw[] = [];

  if (route.path.includes(':') && !route.props) route.props = true;

  const { name, path, component, children, ...rest } = route;
  const vueRoute = { name, path, ...rest } as RouteRecordRaw;

  try {
    if (component) {
      if (isSingleLevelRoute(route)) {
        const { layout, view } = getSingleLevelRouteComponent(component);
        return [{
          path,
          component: layouts[layout],
          meta: { title: route.meta?.title || '' },
          children: [{ name, path: '', component: views[view], ...rest } as RouteRecordRaw]
        }];
      }

      if (isLayout(component)) vueRoute.component = layouts[getLayoutName(component)];
      if (isView(component)) vueRoute.component = views[getViewName(component)];
    }
  } catch (error: any) {
    console.error(`Error transforming route "${route.name}": ${error.toString()}`);
    return [];
  }

  if (children?.length && !vueRoute.redirect) {
    vueRoute.redirect = { name: children[0].name };
  }

  if (children?.length) {
    const childRoutes = children.flatMap(child => transformElegantRouteToVueRoute(child, layouts, views));
    if (isFirstLevelRoute(route)) vueRoute.children = childRoutes;
    else vueRoutes.push(...childRoutes);
  }

  vueRoutes.unshift(vueRoute);
  return vueRoutes;
}

const routeMap: RouteMap = {
  "root": "/",
  "not-found": "/:pathMatch(.*)*",
  "exception": "/exception",
  "exception_403": "/exception/403",
  "exception_404": "/exception/404",
  "exception_500": "/exception/500",
  "document": "/document",
  "document_project": "/document/project",
  "document_project-link": "/document/project-link",
  "document_vue": "/document/vue",
  "document_vite": "/document/vite",
  "document_unocss": "/document/unocss",
  "document_naive": "/document/naive",
  "document_antd": "/document/antd",
  "document_element-plus": "/document/element-plus",
  "document_alova": "/document/alova",
  "403": "/403",
  "404": "/404",
  "500": "/500",
  "dashboard": "/dashboard",
  "iframe-page": "/iframe-page/:url",
  "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?",
  "user-center": "/user-center",
  "subjects": "/subjects",
  "subjects_list": "/subjects/list",
  "question-types": "/question-types",
  "question-types_list": "/question-types/list",
  "questions": "/questions",
  "questions_list": "/questions/list",
  "knowledge-points": "/knowledge-points",
  "knowledge-points_list": "/knowledge-points/list",
  "materials": "/materials",
  "materials_list": "/materials/list",
  "exams": "/exams",
  "exams_list": "/exams/list",
  "exams_sessions": "/exams/sessions",
  "scores": "/scores",
  "scores_list": "/scores/list",
  "users": "/users",
  "users_list": "/users/list",
  "rbac": "/rbac",
  "rbac_permissions": "/rbac/permissions",
  "rbac_roles": "/rbac/roles",
  "rbac_menus": "/rbac/menus",
  "rbac_admins": "/rbac/admins"
};

export function getRoutePath<T extends RouteKey>(name: T) {
  return routeMap[name];
}

export function getRouteName(path: RoutePath) {
  const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];
  return routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;
}
